config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
 
  root "static_pages#landing_page"
  get "plans", to: "static_pages#plans"
  post "plans", to: "static_pages#plans"
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :users, only: [:index, :show]
  resources :problems do
    resources :comments
    get :delete
  end
  
  get "tags/:tag", to: "problems#index", as: :tag
  resources :solutions do
    get :cast_vote, on: :member
  end
  resources :votes
  devise_scope :user do
      get "login", to: "devise/sessions#new"
      get "logout", to: "devise/sessions#destroy"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!
  layout 'naked'
  def home
  end
  def landing_page
    if current_user
      redirect_to problems_path
    end
  end
end

app/views/static_pages/home.html.slim
.row 
  .medium-12.columns
    h1 hello

app/views/static_pages/landing_page.html.slim
#landing-page-wrapper
  .login-form-wrapper.centered
    = simple_form_for(:user, :url => session_path(:user)) do |f| 
        = f.input :email, label: false, required: false, autofocus: true, input_html: {id: "login-email"}, placeholder: 'Email'
        = f.input :password, label: false, required: false, input_html: {id: "login-password"},placeholder: 'Password'
        = f.button :submit, "Log in", class: 'expand' 
        .additional-links.text-center 
          | #{ link_to "Sign up", new_registration_path(:user)} <br>
          | #{ link_to "Forgot your password?", new_password_path(:user)}
    .facebook-button
      button#facebook onclick="location.href='/users/auth/facebook'"Log in with Facebook

app/views/static_pages/plans.html.slim
javascript:
  $(function(){ 
    //when the plan button is clicked
    $("a.plan_select").click(function(){
      //copy the data-plan-id attribute to the #payments_plan_id input
      var data_plan_id = $(this).attr('data-plan-id')
      $("#payments_plan_id").val(data_plan_id)
      console.log("user has selected " + data_plan_id)
    })
  });
  
.row
  .medium-12.columns
    h1 Plans
    = link_to "Plan 1", "#", {class: 'button plan_select', data: { plan_id: "plan_167" } }
    br
    = link_to "Plan 2", "#", {class: 'button plan_select', data: { plan_id: "plan_477" } }
    br
    = link_to "Plan 3", "#", {class: 'button plan_select', data: { plan_id: "plan_9967" } }

    = simple_form_for 'payments' do |f|
      = f.input :plan_id, as: :hidden
      = f.input :cc_number
      = f.button :submit, 'Submit'  