config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
 
  root "static_pages#landing_page"
  get "plans", to: "static_pages#plans"
  post "plans", to: "static_pages#plans"
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :users, only: [:index, :show]
  resources :problems do
    resources :comments
    get :delete
  end
  
  get "tags/:tag", to: "problems#index", as: :tag
  resources :solutions do
    get :cast_vote, on: :member
  end
  resources :votes
  devise_scope :user do
      get "login", to: "devise/sessions#new"
      get "logout", to: "devise/sessions#destroy"
  end
end

app/models/problem.rb
class Problem < ActiveRecord::Base
  acts_as_commentable
  mount_uploader :background_image, BackgroundImageUploader
  belongs_to :user
  
  belongs_to :category
  before_create :set_color
  
  has_many :comments, as: :commentable
  has_many :votes, through: :solutions
  has_many :solutions, dependent: :destroy

  accepts_nested_attributes_for :solutions, :allow_destroy => true, :reject_if => proc { |solution| solution['title'].blank? }

  validate :category_is_present
  validate :have_solutions
  validates :content, length: { in: 10..200 }

  def category_is_present
    if self.category_id.nil?
      errors.add(:base, "You must select a category")
    end
  end

  def have_solutions
    unless solutions.size.in?(2..4)
      errors.add(:base, "Must have at least 2 options but can not have more than 4.")
    end
  end

  def set_color
    self.color = ["#1ba1e2", "#326ada", "#86becb", "#1aa3a3", "#0b5e56"].sample  
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  load_and_authorize_resource :problem
  respond_to :html, :js

  def index
    # @problems = Problem.all
    @category = Category.find_by_name(params[:category]) if params[:category]
    @problems = if @category
      @category.problems
    else
      Problem.all
    end
  end

  def new 
    # load_and_authorize_resource will create the instance variable @problem
    # @problem = Problem.new
    @categories = Category.all
    @problem.solutions.new
  end  

  def create
    @problem = current_user.problems.new(problem_params)
    @categories = Category.all
    if @problem.save
      respond_with(@problem) 
    else
      render :new
    end
  end 

  def show
    @problem = Problem.find_by_id(params[:id])
  end

  def destroy
    @problem.destroy
    render 'delete.js.erb'
  end
  private
  def problem_params
    params.require(:problem).permit(:content, :background_image, :category_id, solutions_attributes: [:title])
  end

end

app/views/problems/_form.html.slim
= simple_form_for @problem, html: {multipart: true} do |f|
  ul.alert
    - @problem.errors.full_messages.each do |message|
      li = message
  = f.input :content, label: false, placeholder: 'Add your dilemma here...'
  = f.input :background_image, as: :file, label: 'Upload a background image for your dilemma or we can choose one for you', class: "add-background-text"
  = f.label :category
  - @categories.each do |cat|
    = radio_button_tag("problem[category_id]", cat.id, @problem.category_id == cat.id)
    span.label = cat.name
    br
  = label(:problem, :options, "Create 2-4 options")
  = f.fields_for :solutions do |builder|
    = render "solution_fields", f: builder
  
  p = link_to_add_fields "+ Add voting option", f, :solutions, 'secondary button'
  
  = f.button :submit, "Create Dilemma", class: "button small"

app/views/problems/_problem.html.slim
li.grid-item.small-12.medium-4.large-3.columns id="#{dom_id(problem)}" 
  div class="inner-problem" style="background-image: url(#{problem.background_image.url}); background-color: #{problem.color};"
    - if can? :destroy, problem
      = link_to "X", problem_path(problem), method: :delete, remote: true, class: 'destroy_problem', data: {confirm: 'Are you sure?'} 
    article
      = link_to problem.content, problem_path(problem), class: 'problem-content' 
      = link_to problem.user.try(:name), problem.user, class: 'problem-author' 

app/views/problems/_solution_fields.html.slim
.fields
  .row
    .medium-12.columns
      = f.input :title, label: false, placeholder: 'Type your voting option here...'
  .row
    .medium-2.medium-offset-10.columns.voting-options
      = link_to_remove_fields "X Delete", f, class: 'remove-problem'

app/views/problems/delete.js.erb
$("#<%= dom_id(@problem) %>").remove();
$('.grid').isotope({
  itemSelector: '.grid-item',
  layoutMode: 'fitRows'
});

app/views/problems/delete.js.slim
$("<%= @problem_element %>").remove();
$('.grid').isotope({
  itemSelector: '.grid-item',
  layoutMode: 'fitRows'
});

app/views/problems/index.html.slim
.page-title
  h1 = @category ? "...#{@category.name}" : "All..."

  ul.grid
    = render @problems

app/views/problems/new.html.slim
.problem-new-wrapper
  .row
    .medium-12.medium-offset-2.columns
      .page-title
        h1 ...Add a dilemma for the community to vote on
        .row
          .medium-8.columns
            = render 'form'

app/views/problems/show.html.slim
.page-title
  h1 ...#{ @problem.category.name } 
  .row
    .medium-6.medium-centered.columns
      .problem-image-container
        .problem-image style="background: url('#{image_url @problem.background_image }'); background-color: #{@problem.color};" 
          .problem-inner
            .problem-text
              = @problem.content
              = link_to @problem.user.try(:name), @problem.user, class: 'problem-user'
  .row
    .medium-6.medium-centered.columns
      ul.solutions-list
        - @problem.solutions.each do |solution|
          li 
            .row
              .medium-6.columns
                p #{solution.title}
              .medium-6.columns
                - if user_has_voted_on_problem?(current_user, @problem)
                  p Vote has been cast!
                - else
                  - if problem_belongs_to_current_user?
                    = render 'solutions/voted_on_solution_message'
                  - else
                    = link_to "Cast Vote", cast_vote_solution_path(solution), remote: true, class: 'button tiny'
      - if user_has_voted_on_problem?(current_user, @problem) || problem_belongs_to_current_user? && @problem.votes.count >= 1
        = pie_chart(piechart_data(@problem.solutions))
          
      = render 'comments/list', commentable: @problem if user_signed_in? 