config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
 
  root "static_pages#landing_page"
  get "plans", to: "static_pages#plans"
  post "plans", to: "static_pages#plans"
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :users, only: [:index, :show]
  resources :problems do
    resources :comments
    get :delete
  end
  
  get "tags/:tag", to: "problems#index", as: :tag
  resources :solutions do
    get :cast_vote, on: :member
  end
  resources :votes
  devise_scope :user do
      get "login", to: "devise/sessions#new"
      get "logout", to: "devise/sessions#destroy"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_devise_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :set_categories_for_nav


  def configure_devise_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u| u.permit(:email, :password, :password_confirmation, :name, :image) 
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password, :image)
    end
  end

  def set_categories_for_nav
    @categories = Category.all
  end

  def after_sign_in_path_for(resource)
    problems_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f, style)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)", class: style)
  end
  
  def link_to_add_fields(name, f, association, style)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")", class: style)
  end
  
end

app/views/application/_flash_messages.html.slim
- if flash[:alert].present?
  p class="system-alert flash-alert alert-box" = flash[:alert]
- if flash[:error].present?
  p class="system-alert flash-error alert-box alert" = flash[:error]
- if flash[:notice].present?
  p class="system-alert flash-notice alert-box success" = flash[:notice]  

app/views/application/_nav.html.slim
.sticky.fixed
  nav.top-bar data-topbar="data-topbar"
    ul.title-area
      li.name
        h1 = link_to "Dilemma".html_safe, root_path       
      li.toggle-topbar.menu-icon
        a href="#"
          span Menu
    - if user_signed_in? 
      section.top-bar-section
        ul.left
          li = link_to "Add Dilemma", new_problem_path
    section.top-bar-section
      ul.right
        - if user_signed_in?
          li.has-dropdown
            = link_to "Browse", "#"
            ul.dropdown
              li = link_to "All", problems_path
              - @categories.each do |category|
                li= link_to category.name, problems_path(category: category.name)
          li = link_to current_user do
            - if current_user.image.present?
              div.profile-square = image_tag(current_user.image.url)
            - else
              div.profile-square.letter-square = current_user.name[0].capitalize 
            = "Profile"
          li.has-dropdown
            = link_to "Account", "#"
            ul.dropdown
              li = link_to "Edit Profile", edit_user_registration_path
              li = link_to "Logout", logout_path
        - else
          li = link_to "Sign up", new_user_registration_path
            